version: '3'
services:
  db:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      DB_HOST_NAME: db
    volumes:
     # DBデータをホストに保存
      - ./mysql/db/volumes:/var/lib/mysql
  web:
    build: ./web
    command: /app/bin/bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - ./web/app:/app
    environment:
      RAILS_ENV: development
    depends_on:
      - db
