apiVersion: apps/v1
kind: Deployment
metadata:
  name: weightapp-mysql
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-config-volume
        configMap:
          name: mysql-config
          items:
          - key: my.cnf
            path: my.cnf
      containers:
        - name: mysql
          image: mysql:8.0
          envFrom:
          - secretRef:
              name: mysql-auth
          ports:
          - containerPort: 3306
          volumeMounts:
            - name: mysql-config-volume
              mountPath: /etc/mysql/conf.d/
