apiVersion: v1
kind: Pod
metadata:
  name: rails
spec:
  volumes:
  - name: rails-app-volume
    hostPath:
      path: "/Users/richter/develop/docker/hody_sample/nginx-unicorn-rails/web/app"
  containers:
  - name: rails
    image: nginx-unicorn-rails_web:latest
    imagePullPolicy: IfNotPresent
    command: ["/app/bin/bundle", "exec", "rails", "s", "-p", "3000", "-b", "'0.0.0.0'"]
    ports:
    - containerPort: 3000
    volumeMounts:
      - name: rails-app-volume
        mountPath: /app
